### ISSUE TITLE
Python error on skip-preview-namelist in the run script

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#1690]
On Mira/Cetus, the run script case.run (called by case.submit) is interrupted due to the following error:
```
Traceback (most recent call last):
  File "./case.run", line 86, in <module>
    _main_func(__doc__)
  File "./case.run", line 79, in _main_func
    caseroot, skip_pnl = parse_command_line(sys.argv, description)
  File "./case.run", line 67, in parse_command_line
    if args.skip_preview_namelist is None:
AttributeError: 'Namespace' object has no attribute 'skip_preview_namelist'
```
This Python error is introduced by PR #1471.
In config/acme/machines/template.case.run, --skip-preview-namelist is added to the parser AFTER the arguments are already parsed, which is at a wrong place.
```
args = CIME.utils.parse_args_and_handle_standard_logging_options(args, parser)
parser.add_argument("--skip-preview-namelist", action="store_true",
                    help="Skip calling preview-namelist during case.run")  
...
if args.skip_preview_namelist is None:
    args.skip_preview_namelist = False
```
In config/cesm/machines/template.case.run, the calling sequences are correct.
```
parser.add_argument("--skip-preview-namelist", action="store_true",
                    help="Skip calling preview-namelist during case.run")

args = CIME.utils.parse_args_and_handle_standard_logging_options(args, parser)
```

**Comment by jgfouca** [comment]
Assigning to @erichlf since he did the --skip-preview-namelist work.
