### ISSUE TITLE
Need to update minimum python version check

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#4032]
This line

https://github.com/esmci/cime/blob/master/scripts/Tools/standard_script_setup.py#L17

needs to be updated.

What is the minimum version now? 3.5? I know that, according to https://github.com/ESMCI/cime/issues/3965, we want 3.6 or later, but I'm not sure if we have any 3.6-specific features yet - though we could change that to 3.6 if we think we'll have 3.6-specific features soon.

I'm labeling this critical because I think we're going to start getting help requests from confused users soon unless we do this.

**Comment by rljacob** [comment]
I asked @jgfouca a couple of days ago and he said 3.6 is the minimum.

**Comment by billsacks** [comment]
Okay, I have updated #4035 to require 3.6 or later.

**Comment by rljacob** [comment]
This needs to be updated again.

**Comment by jgfouca** [comment]
Yep. I think 3.11 is the minimum now.

**Comment by jedwards4b** [comment]
No - we test with 3.8 in the github workflow.

**Comment by jgfouca** [comment]
We should maybe look at some of the code in ERP then. There is some datetime stuff in there that won't work with 3.8

**Comment by jgfouca** [comment]
```
          File "/lustre/orion/cli115/scratch/acmetest/testing/E3SM/cime/CIME/SystemTests/erp.py", line 29, in __init__
            **kwargs
          File "/lustre/orion/cli115/scratch/acmetest/testing/E3SM/cime/CIME/SystemTests/restart_tests.py", line 30, in __init__
            **kwargs
          File "/lustre/orion/cli115/scratch/acmetest/testing/E3SM/cime/CIME/SystemTests/system_tests_compare_two.py", line 146, in __init__
            self._setup_cases_if_not_yet_done()
          File "/lustre/orion/cli115/scratch/acmetest/testing/E3SM/cime/CIME/SystemTests/system_tests_compare_two.py", line 450, in _setup_cases_if_not_yet_done
            self._setup_cases()
          File "/lustre/orion/cli115/scratch/acmetest/testing/E3SM/cime/CIME/SystemTests/system_tests_compare_two.py", line 540, in _setup_cases
            self._case_one_setup()
          File "/lustre/orion/cli115/scratch/acmetest/testing/E3SM/cime/CIME/SystemTests/restart_tests.py", line 36, in _case_one_setup
            self._set_restart_interval()
          File "/lustre/orion/cli115/scratch/acmetest/testing/E3SM/cime/CIME/SystemTests/system_tests_common.py", line 204, in _set_restart_interval
            startdatetime = datetime.fromisoformat(startdate) + timedelta(
        AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by jedwards4b** [comment]
I can't tell what version of python that was from.   This https://stackoverflow.com/questions/60266554/type-object-datetime-datetime-has-no-attribute-fromisoformat suggests that 3.8 should work.

**Comment by jedwards4b** [comment]
See also https://docs.python.org/3/library/datetime.html#datetime-objects

**Comment by rljacob** [comment]
@jgfouca this conversation should maybe be moved to https://github.com/ESMCI/cime/pull/4761
